version: "2"

services:

  indico-celery:
    image: fermented/indico-worker:stable
    command: celery
    depends_on:
      - indico-db
    links:
      - "indico-db:indico-db"
      - "indico-redis:indico-redis"
    volumes_from:
      - indico-worker
    user: ${WORKER_USER}
    labels:
      edu.stanford.slac.indico.service: celery
      edu.stanford.slac.indico.role: "Indico celery service"
