version: "2.1"

services:

  indico-redis:
    image: redis:alpine
    networks: [indico_net]
    restart: always
    volumes:
      - redis-data:/data
    labels:
      edu.stanford.slac.indico.service: redis
      edu.stanford.slac.indico.role: "Redis service for Indico"

  indico-db:
    image: postgres:12
    networks: [indico_net]
#    ports:
#      - 5432:5432
    volumes:
      - ${INDICO_DIR:-/opt/indico-docker}/postgres:/var/lib/postgresql/data
    user: ${INDICO_USER}
    restart: unless-stopped
    labels:
      edu.stanford.slac.indico.service: database
      edu.stanford.slac.indico.role: "Postgres database for Indico"

  indico-db-backup:
    image: fermented/indico-db-backup:${INDICO_TAG:-stable}
    depends_on:
      - indico-db
    networks: [indico_net]
    # user: ${INDICO_USER}
    restart: unless-stopped
    volumes:
      - ${INDICO_DIR:-/opt/indico-docker}/data:/opt/indico/data
      - ${INDICO_DIR:-/opt/indico-docker}/backups:/backups
    labels:
      edu.stanford.slac.indico.service: db-backup
      edu.stanford.slac.indico.role: "Database backup cron job for Indico"

  indico-worker:
    image: fermented/indico-worker:${INDICO_TAG:-stable}
    depends_on:
      - indico-redis
      - indico-db
    networks: [indico_net]
    volumes:
      - ${INDICO_DIR:-/opt/indico-docker}/data:/opt/indico/data
      - ${INDICO_DIR:-/opt/indico-docker}/scratch:/opt/indico/scratch
    user: ${INDICO_USER}
    restart: unless-stopped
    labels:
      edu.stanford.slac.indico.service: worker
      edu.stanford.slac.indico.role: "Indico worker"

  indico-celery:
    image: fermented/indico-worker:${INDICO_TAG:-stable}
    command: celery
    depends_on:
      - indico-db
    networks: [indico_net]
    volumes_from:
      - indico-worker
    user: ${INDICO_USER}
    restart: unless-stopped
    labels:
      edu.stanford.slac.indico.service: celery
      edu.stanford.slac.indico.role: "Indico celery service"

  indico-httpd:
    image: fermented/indico-httpd:${INDICO_TAG:-stable}
    depends_on:
      - indico-worker
    ports:
      - 443:443
    volumes_from:
      - indico-worker
    networks: [indico_net]
    volumes:
      - "${INDICO_DIR:-/opt/indico-docker}/ssl:/etc/ssl/indico:ro"
    restart: unless-stopped
    labels:
      edu.stanford.slac.indico.service: httpd
      edu.stanford.slac.indico.role: "Web server for Indico"

  indico-collectd:
    image: fermented/indico-collectd:${INDICO_TAG:-stable}
    depends_on:
      - indico-redis
      - indico-db
      - indico-worker
      - indico-httpd
    networks: [indico_net]
    privileged: true
    pid: "host"
    volumes:
      - ${INDICO_DIR:-/opt/indico-docker}/data:/opt/indico/data
      - ${INDICO_DIR:-/opt/indico-docker}/scratch:/opt/indico/scratch
    environment:
      INDICO_MON: ${INDICO_MON}

networks:
  indico_net:
    name: indico-net

volumes:
  redis-data:
