version: "2.1"

services:

  indico-redis:
    image: redis:alpine
    labels:
      edu.stanford.slac.indico.service: redis
      edu.stanford.slac.indico.role: "Redis service for Indico"

  indico-db:
    image: fermented/indico-db:${INDICO_TAG:-stable}
#    ports:
#      - 5432:5432
    volumes:
      - /opt/indico/docker/postgres:/var/lib/postgresql/data
    labels:
      edu.stanford.slac.indico.service: database
      edu.stanford.slac.indico.role: "Postgres database for Indico"

  indico-db-backup:
    image: fermented/indico-db-backup:${INDICO_TAG:-stable}
    volumes:
      - /opt/indico/docker/postgres:/var/lib/postgresql/data
    links:
      - "indico-db:indico-db"
    volumes:
       - /opt/indico/docker/data:/opt/indico/data
    labels:
      edu.stanford.slac.indico.service: db-backup
      edu.stanford.slac.indico.role: "Database backup cron job for Indico"

  indico-worker:
    image: fermented/indico-worker:${INDICO_TAG:-stable}
    depends_on:
      - indico-redis
      - indico-db
    links:
      - "indico-db:indico-db"
      - "indico-redis:indico-redis"
    volumes:
       - /opt/indico/docker/data:/opt/indico/data
       - /opt/indico/docker/scratch:/opt/indico/scratch
    user: ${WORKER_USER}
    labels:
      edu.stanford.slac.indico.service: worker
      edu.stanford.slac.indico.role: "Indico worker"

  indico-httpd:
    image: fermented/indico-httpd:${INDICO_TAG:-stable}
    depends_on:
      - indico-worker
    ports:
      - 444:443
    volumes_from:
      - indico-worker
    links:
      - "indico-worker:indico-worker"
    volumes:
      - "/opt/indico/docker/ssl:/etc/ssl/indico:ro"
    labels:
      edu.stanford.slac.indico.service: httpd
      edu.stanford.slac.indico.role: "Web server for Indico"
