version: "2"

services:

  indico-db-backup:
    build: ./indico-db-backup
    image: fermented/indico-db-backup:latest

  indico-worker:
    build: ./indico-worker
    image: fermented/indico-worker:latest

  indico-httpd:
    build: ./indico-httpd
    image: fermented/indico-httpd:latest

  indico-collectd:
    build: ./indico-collectd
    image: fermented/indico-collectd:latest
