version: "2"

services:

  indico-db:
    build: ./indico-db
    image: fermented/indico-db:latest

  indico-latex:
    build: ./indico-latex
    image: fermented/indico-latex:latest

  indico-worker:
    build: ./indico-worker
    image: fermented/indico-worker:latest

  indico-httpd:
    build: ./indico-httpd
    image: fermented/indico-httpd:latest
