version: "2.1"

services:

  indico-celery:
    image: fermented/indico-worker:${INDICO_TAG:-stable}
    command: celery
    depends_on:
      - indico-db
    links:
      - "indico-db:indico-db"
      - "indico-redis:indico-redis"
    volumes_from:
      - indico-worker
    user: ${WORKER_USER}
    restart: unless-stopped
    labels:
      edu.stanford.slac.indico.service: celery
      edu.stanford.slac.indico.role: "Indico celery service"
